### ISSUE TITLE
Skillowanie pojedyńczych skoków

### ISSUE THREAD

**Issue by AyBiCi** [rycerz125/GrubasParkourPlugin#11]
Wiele graczy chciałoby popróbować przechodzenie pojedynczych części mapy, fajnie byłoby stworzyć do tego jakąś szybką możliwość np. specjalny tryb skillowania skoków.

**Comment by rycerz125** [comment]
Istnieje już taka opcja. Po wpisaniu komendy "/cp" graczowi zatrzymuje parkour. Nie może go wtedy rozpocząć ani skończyć dopóki nie dołączy jeszcze raz na mapę. Backblocki dalej cofają, tyle że do miejsca, w którym gracz wpisał tę komendę.  Nie widać wizualnego timera. Gdy gracz nie jest na parkourze podczas wpisania tej komendy, to wyświetla się odpowiedni komunikat "Musisz rozpocząć parkour!".
