### ISSUE TITLE
Level System

### ISSUE THREAD

**Issue by MrKaratio1337** [rycerz125/GrubasParkourPlugin#18]
Można by było dodać system leveli

**Comment by rycerz125** [comment]
Przedstawiam jak ja to widzę:
- system leveli będzie bazować na ilości expa gracza,
- exp będzie się zdobywać przechodząc parkoury,
- za przejście mapy będzie stały poziom expa niezależnie ile razy gracz już ją przeszedł,
- ilość expa odpowiadająca mapie będzie obliczana automatycznie z jej długości i kategorii i będzie konfigurowalna ręcznie,
- należy zaprogramować kalkulator expa tak, żeby obliczyć graczom jego ilość zebraną przed wprowadzeniem systemu leveli.

**Comment by rycerz125** [comment]
System leveli został skończony wraz z commitem b51f8c759d5992d98371fa0447639f7bf937139c
wątek uważam za zamknięty.
