### ISSUE TITLE
Niejasność wychodzenia z komendy playdemo

### ISSUE THREAD

**Issue by AyBiCi** [rycerz125/GrubasParkourPlugin#5]
Trzeba jakoś pokazać, jak wychodzi się z playdemo, może być np. wiadomość na czacie

**Comment by rycerz125** [comment]
Dodano czerwony barwnik o nazwie _Quit Demo_ który pojawia się przy oglądaniu demek. Po jego kliknięciu gracz zostaje teleportowany na start parkoura i itemek znika.
commit 050f343a2e99da3ba45fa2fe65e45931f5e0da04
