### ISSUE TITLE
Usunięcie fixa na kolizję graczy

### ISSUE THREAD

**Issue by AyBiCi** [rycerz125/GrubasParkourPlugin#9]
Jak można to ustawić w PaperSpigocie, to tutaj nie trzeba robić żadnych obejść.

**Comment by rycerz125** [comment]
Zakomentowano te linie, bo przy Bukkicie lub Spigocie nie ma takiej opcji w configu. Tylko PaperSpigot.
commit 5fc691aed8ea3e15e9f98678c9b78652b87ce831
